### ISSUE TITLE
DB Access menu page is not loading in 4.2.3

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-dbaccess-plugin#2]
DB Access 1.2.1 version is not working correctly with Openfire 4.2.3 (works ok with the latest 4.3 branch). I guess it is not compatible with the latest branch, but this is not reflected in plugin's xml. For me it just shows blank page. User [reports](https://discourse.igniterealtime.org/t/noclassdeffounderror-in-dbaccess-1-2-1-plugin/83989) such exception:

2019.01.23 19:58:05 org.jivesoftware.openfire.container.PluginServlet - An unexpected problem occurred while attempting to register servlets for plugin ‘org.jivesoftware.openfire.plugin.DbAccessPlugin@5b329a3a’.
java.lang.NoClassDefFoundError: org/apache/jasper/runtime/JspSourceImports
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.jivesoftware.openfire.container.PluginManager.loadClass(PluginManager.java:958)
at org.jivesoftware.openfire.container.PluginServlet.registerServlets(PluginServlet.java:151)
at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:568)
at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:276)
at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:264)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.jasper.runtime.JspSourceImports
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by GregDThomas** [comment]
I found this with the Hazelcast plugin. There are two options
a) Limit yourself to 4.3.0 or higher
b) Simply add a tiny class to the plugin. The missing class is an interface that the new (in 4.3.0) JSP compiler references  - https://github.com/igniterealtime/openfire-hazelcast-plugin/blob/master/src/java/org/apache/jasper/runtime/JspSourceImports.java

**Comment by guusdk** [comment]
B!

**Comment by akrherz** [comment]
Ignorance here, but can this class just be added to Openfire, so that every plugin does not have to be updated?

**Comment by GregDThomas** [comment]
Well, it's already included in Openfire 4.3, it's just missing from Openfire 4.0, 4.1, 4.2. So you could go back and put in there ...

**Comment by wrooot** [comment]
After Greg's comment on another issue i wonder if this issue was misunderstood. DB Access works with new Openfire, so it is not missing anything for 4.3. But it has something incompatible with 4.2.3 version now.

**Comment by wrooot** [comment]
Oh, i think i get it now. So this new part is needed, because new compiler needs it and if it is not included when 4.2.3 can't work with it, but 4.3.0 already has it included.

**Comment by wrooot** [comment]
We need to release new version and add this to changelog.

**Comment by GregDThomas** [comment]
Changelog updated + released
